name: Build and Upload Debian Package

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Install build dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y build-essential debhelper dh-python python3-all

      - name: Prepare orig.tar.gz
        run: |
          cd ..
          tar czf okadminfinder_1.1.0.orig.tar.gz okadminfinder
          ls -ll

      - name: Build Debian package
        run: |
          dpkg-buildpackage -rfakeroot -uc -us

      - name: Move Debian package to working directory
        run: |
          mv ../*.deb .

      - name: List files in output directory
        run: |
          cd ..
          ls -ll  # Verify files are present

      - name: Upload Debian package artifacts
        uses: actions/upload-artifact@v2
        with:
          name: okadminfinder
          path: okadminfinder_*.deb
