name: Build and Upload Debian Package

on:
  push:
    tags:
      - '*' # This will trigger the workflow for any tag that starts with any character

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install build dependencies
        run: |
          python3 -V
          curl -sSL https://install.python-poetry.org | python3 -
          export PATH=$HOME/.local/bin:$PATH
          sudo apt-get update
          sudo apt-get install -y build-essential debhelper dh-python python3-all pybuild-plugin-pyproject

      - name: Prepare orig.tar.gz
        run: |
          cd ..
          tar czf okadminfinder_${{ github.ref_name }}.orig.tar.gz okadminfinder
          ls -ll

      - name: Build Debian package
        run: |
          export PYTHON=python3
          dpkg-buildpackage -rfakeroot -uc -us

      - name: Copy Debian package to working directory
        run: |
          mkdir builds
          cp ../okadminfinder_* builds/

      - name: List files in builds directory
        run: |
          ls -ll builds/ # Verify files are present

      - name: Release
        uses: softprops/action-gh-release@v2
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: |
            builds/okadminfinder_${{ github.ref_name }}-1_all.deb
