name: Build and Upload Debian Package

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Install build dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y build-essential debhelper dh-python python3-all

      - name: Prepare orig.tar.gz
        run: |
          cd ..
          tar czf okadminfinder_1.1.0.orig.tar.gz okadminfinder

      - name: Build Debian package
        run: |
          cd ../okadminfinder
          dpkg-buildpackage -rfakeroot -uc -us

      - name: List files in output directory
        run: |
          ls -l ../okadminfinder/*.deb  # Verify files are present

      - name: Upload Debian package artifacts
        if: success()  # Only upload artifacts if the previous steps were successful
        run: |
          cd ..
          ls -l okadminfinder/*.deb  # Double check files are visible from this directory
          echo "::set-env name=DEB_FILES::$(echo okadminfinder/*.deb)"
        uses: actions/upload-artifact@v2
        with:
          name: okadminfinder-deb-package
          path: ${{ env.DEB_FILES }}
          if-no-files-found: warn
